// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAUIuzdKxlcPbbTDI02M1rdMXRqCfbEXE',
    appId: '1:755869531750:web:1d0df16d79552a678af7a7',
    messagingSenderId: '755869531750',
    projectId: 'sunshine-cdefb',
    authDomain: 'sunshine-cdefb.firebaseapp.com',
    storageBucket: 'sunshine-cdefb.appspot.com',
    measurementId: 'G-TR6KPB5P87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeag0-wyf6wHkMBFXEsYrNDy5JmFI9q1w',
    appId: '1:755869531750:android:78afc66c103966ca8af7a7',
    messagingSenderId: '755869531750',
    projectId: 'sunshine-cdefb',
    storageBucket: 'sunshine-cdefb.appspot.com',
  );
}
